import { Company } from "./types";

export const companies: Company[] = [
  // ── AI / ML ──────────────────────────────────────────────
  {
    id: "synth-ai",
    name: "SynthAI",
    website: "https://www.synthesia.io",
    description:
      "Builds foundation models for synthetic data generation, helping enterprises train ML models without real user data.",
    sector: "AI/ML",
    stage: "Series A",
    location: "San Francisco",
    foundedYear: 2023,
    teamSize: "11-50",
    founders: ["Maya Chen", "Raj Patel"],
    tags: ["synthetic-data", "foundation-models", "privacy"],
  },
  {
    id: "cortex-labs",
    name: "Cortex Labs",
    website: "https://www.cortex.io",
    description:
      "AI-powered internal developer portal that scores service quality, ownership clarity, and production readiness.",
    sector: "Developer Tools",
    stage: "Seed",
    location: "New York",
    foundedYear: 2024,
    teamSize: "1-10",
    founders: ["Nikhil Bhatia"],
    tags: ["developer-portal", "platform-engineering", "AI"],
  },
  {
    id: "voxel-health",
    name: "Voxel Health",
    website: "https://www.voxelhealth.com",
    description:
      "Uses computer vision to detect early-stage tumors in radiology scans with 40% higher accuracy than traditional methods.",
    sector: "Healthtech",
    stage: "Series A",
    location: "Boston",
    foundedYear: 2022,
    teamSize: "11-50",
    founders: ["Dr. Sarah Kim", "James Olson"],
    tags: ["computer-vision", "radiology", "diagnostics"],
  },
  {
    id: "greenvolt",
    name: "GreenVolt",
    website: "https://www.greenvolt.com",
    description:
      "Optimizes commercial building energy usage using IoT sensors and predictive ML, reducing costs by 30%.",
    sector: "Climatetech",
    stage: "Seed",
    location: "Berlin",
    foundedYear: 2024,
    teamSize: "1-10",
    founders: ["Lukas Weber", "Anika Sharma"],
    tags: ["energy", "IoT", "sustainability", "ML"],
  },
  {
    id: "paystream",
    name: "PayStream",
    website: "https://www.paystream.io",
    description:
      "Embedded payments infrastructure for SaaS platforms, enabling integrated billing, invoicing, and revenue recognition.",
    sector: "Fintech",
    stage: "Series A",
    location: "London",
    foundedYear: 2023,
    teamSize: "11-50",
    founders: ["Oliver Grant", "Priya Mehta"],
    tags: ["payments", "embedded-finance", "SaaS"],
  },
  {
    id: "querycraft",
    name: "QueryCraft",
    website: "https://www.querycraft.dev",
    description:
      "Natural language to SQL tool that lets non-technical users query databases using conversational English.",
    sector: "AI/ML",
    stage: "Pre-Seed",
    location: "Toronto",
    foundedYear: 2025,
    teamSize: "1-10",
    founders: ["Elena Vasquez"],
    tags: ["NLP", "databases", "analytics", "AI"],
  },
  {
    id: "stackpulse",
    name: "StackPulse",
    website: "https://www.stackpulse.io",
    description:
      "Automated incident response platform that orchestrates runbooks across cloud services and reduces MTTR by 60%.",
    sector: "Developer Tools",
    stage: "Series A",
    location: "San Francisco",
    foundedYear: 2022,
    teamSize: "51-200",
    founders: ["David Raz", "Leonid Belkind"],
    tags: ["incident-response", "automation", "DevOps"],
  },
  {
    id: "nutrigenix",
    name: "NutriGenix",
    website: "https://www.nutrigenix.com",
    description:
      "Personalized nutrition platform using genomic data and gut microbiome analysis to create tailored meal plans.",
    sector: "Healthtech",
    stage: "Seed",
    location: "San Francisco",
    foundedYear: 2024,
    teamSize: "1-10",
    founders: ["Dr. Mei Lin", "Carlos Hernandez"],
    tags: ["genomics", "nutrition", "personalization"],
  },
  {
    id: "carbonledger",
    name: "CarbonLedger",
    website: "https://www.carbonledger.io",
    description:
      "Blockchain-based carbon credit verification and trading platform for enterprise sustainability programs.",
    sector: "Climatetech",
    stage: "Series A",
    location: "London",
    foundedYear: 2023,
    teamSize: "11-50",
    founders: ["Emma Clarke", "Vikram Singh"],
    tags: ["carbon-credits", "blockchain", "ESG"],
  },
  {
    id: "mosaicml",
    name: "MosaicData",
    website: "https://www.mosaicml.com",
    description:
      "Data pipeline orchestration for ML teams — unifies ingestion, transformation, feature engineering, and model serving.",
    sector: "Data Infrastructure",
    stage: "Seed",
    location: "New York",
    foundedYear: 2024,
    teamSize: "1-10",
    founders: ["Alex Thompson"],
    tags: ["data-pipelines", "MLOps", "feature-store"],
  },
  {
    id: "vaultedge",
    name: "VaultEdge",
    website: "https://www.vaultedge.ai",
    description:
      "AI-powered document processing for insurance underwriting — extracts, classifies, and validates policy documents.",
    sector: "AI/ML",
    stage: "Series A",
    location: "New York",
    foundedYear: 2022,
    teamSize: "11-50",
    founders: ["Kevin Liang", "Sofia Morales"],
    tags: ["document-AI", "insurance", "underwriting"],
  },
  {
    id: "tidepay",
    name: "TidePay",
    website: "https://www.tidepay.co",
    description:
      "Cross-border payroll solution for remote-first companies, handling compliance and payments in 80+ countries.",
    sector: "Fintech",
    stage: "Seed",
    location: "Toronto",
    foundedYear: 2024,
    teamSize: "1-10",
    founders: ["Hannah Lee", "Arjun Desai"],
    tags: ["payroll", "remote-work", "cross-border"],
  },
  {
    id: "codeweave",
    name: "CodeWeave",
    website: "https://www.codeweave.dev",
    description:
      "AI code review assistant that provides context-aware suggestions, detects anti-patterns, and enforces team standards.",
    sector: "Developer Tools",
    stage: "Pre-Seed",
    location: "Berlin",
    foundedYear: 2025,
    teamSize: "1-10",
    founders: ["Max Richter", "Yuki Tanaka"],
    tags: ["code-review", "AI", "developer-experience"],
  },
  {
    id: "helios-energy",
    name: "Helios Energy",
    website: "https://www.heliosenergy.com",
    description:
      "Perovskite solar cell manufacturer achieving 30%+ efficiency at 40% lower cost than traditional silicon panels.",
    sector: "Climatetech",
    stage: "Series B",
    location: "Boston",
    foundedYear: 2021,
    teamSize: "51-200",
    founders: ["Dr. James Park"],
    tags: ["solar", "materials-science", "manufacturing"],
  },
  {
    id: "medflow",
    name: "MedFlow",
    website: "https://www.medflow.health",
    description:
      "Clinical workflow automation for hospitals — reduces nurse administrative burden by 50% through voice-driven charting.",
    sector: "Healthtech",
    stage: "Series A",
    location: "San Francisco",
    foundedYear: 2023,
    teamSize: "11-50",
    founders: ["Dr. Rachel Green", "Tom Harris"],
    tags: ["clinical-workflow", "voice-AI", "hospitals"],
  },
  {
    id: "driftless",
    name: "Driftless",
    website: "https://www.driftless.io",
    description:
      "Infrastructure-as-code drift detection — continuously monitors cloud resources and auto-remediates configuration drift.",
    sector: "Developer Tools",
    stage: "Seed",
    location: "San Francisco",
    foundedYear: 2024,
    teamSize: "1-10",
    founders: ["Ben Foster"],
    tags: ["IaC", "cloud-security", "DevOps"],
  },
  {
    id: "ledgr",
    name: "Ledgr",
    website: "https://www.ledgr.finance",
    description:
      "Real-time treasury management for SMBs — cash flow forecasting, multi-bank aggregation, and automated sweep accounts.",
    sector: "Fintech",
    stage: "Pre-Seed",
    location: "London",
    foundedYear: 2025,
    teamSize: "1-10",
    founders: ["George Campbell"],
    tags: ["treasury", "SMB", "cash-flow"],
  },
  {
    id: "neurograph",
    name: "NeuroGraph",
    website: "https://www.neurograph.ai",
    description:
      "Knowledge graph construction from unstructured enterprise data using LLMs — enables semantic search across internal docs.",
    sector: "AI/ML",
    stage: "Seed",
    location: "Toronto",
    foundedYear: 2024,
    teamSize: "1-10",
    founders: ["Omar Hassan", "Lisa Xu"],
    tags: ["knowledge-graphs", "LLM", "enterprise-search"],
  },
  {
    id: "aquawise",
    name: "AquaWise",
    website: "https://www.aquawise.tech",
    description:
      "Smart water management using satellite imagery and AI to detect leaks and optimize municipal water distribution.",
    sector: "Climatetech",
    stage: "Seed",
    location: "Berlin",
    foundedYear: 2024,
    teamSize: "1-10",
    founders: ["Maria Schmidt", "Kwame Asante"],
    tags: ["water", "satellite", "AI", "municipal"],
  },
  {
    id: "shiftmed",
    name: "ShiftMed",
    website: "https://www.shiftmed.com",
    description:
      "On-demand healthcare staffing marketplace connecting nurses with facilities, using predictive demand modeling.",
    sector: "Healthtech",
    stage: "Series B",
    location: "New York",
    foundedYear: 2021,
    teamSize: "51-200",
    founders: ["Todd Simons"],
    tags: ["staffing", "marketplace", "healthcare"],
  },
  {
    id: "terraflux",
    name: "TerraFlux",
    website: "https://www.terraflux.io",
    description:
      "Geothermal energy exploration platform using ML to analyze subsurface data and identify optimal drilling sites.",
    sector: "Climatetech",
    stage: "Series A",
    location: "San Francisco",
    foundedYear: 2023,
    teamSize: "11-50",
    founders: ["Amanda Brooks", "Dr. Ian Wells"],
    tags: ["geothermal", "ML", "energy-exploration"],
  },
  {
    id: "pipedream",
    name: "PipeDream",
    website: "https://www.pipedream.com",
    description:
      "Serverless integration platform — connect APIs, run workflows, and build event-driven architectures with minimal code.",
    sector: "Developer Tools",
    stage: "Series A",
    location: "San Francisco",
    foundedYear: 2022,
    teamSize: "11-50",
    founders: ["Dylan Sather", "Tod Sacerdoti"],
    tags: ["serverless", "integrations", "workflow-automation"],
  },
  {
    id: "finwise",
    name: "FinWise",
    website: "https://www.finwise.ai",
    description:
      "AI financial advisor for Gen Z — budgeting, investing, and credit building with conversational UI and gamification.",
    sector: "Fintech",
    stage: "Seed",
    location: "New York",
    foundedYear: 2024,
    teamSize: "1-10",
    founders: ["Zoe Martinez", "Jake Collins"],
    tags: ["personal-finance", "AI", "Gen-Z", "neobank"],
  },
  {
    id: "embedchain",
    name: "EmbedChain",
    website: "https://www.embedchain.ai",
    description:
      "Open-source RAG framework that lets developers build AI-powered chat over any data source in under 10 lines of code.",
    sector: "AI/ML",
    stage: "Seed",
    location: "San Francisco",
    foundedYear: 2024,
    teamSize: "1-10",
    founders: ["Taranjeet Singh"],
    tags: ["RAG", "open-source", "LLM", "developer-tools"],
  },
  {
    id: "complianceai",
    name: "ComplianceAI",
    website: "https://www.compliance.ai",
    description:
      "Regulatory change management platform using NLP to track, interpret, and action regulatory updates across jurisdictions.",
    sector: "Fintech",
    stage: "Series A",
    location: "London",
    foundedYear: 2022,
    teamSize: "11-50",
    founders: ["Kayvan Alikhani"],
    tags: ["regtech", "NLP", "compliance", "regulatory"],
  },
];

// Helpers to extract unique filter values from data
export const sectors = [...new Set(companies.map((c) => c.sector))].sort();
export const stages = ["Pre-Seed", "Seed", "Series A", "Series B"];
export const locations = [...new Set(companies.map((c) => c.location))].sort();
export const teamSizes = ["1-10", "11-50", "51-200", "201-500"];
